baseURL = "https://virajbhatnagar.me"
languageCode = "en-us"
title = "Everyday CS"
paginate = 20
pygmentsUseClasses = true
pygmentsCodefences = true

[params]
subtitle = "Viraj Bhatnagar's Tech Blog"

[taxonomies]
   tag = "tags"

[menu]
   [[menu.header]]
      identifier = "about-me"
      name = "About Me"
      url = "/"
      weight = 1

   [[menu.header]]
      identifier = "journals"
      name = "Journals"
      url = "/journals"
      weight = 2
