baseURL = "https://virajbhatnagar.me"
languageCode = "en-us"
title = "Everyday CS"
paginate = 20
pygmentsUseClasses = true
pygmentsCodefences = true

[params]
subtitle = "bytes of wisdom"

[taxonomies]
   tag = "tags"

[menu]
   [[menu.header]]
      identifier = "about-me"
      name = "About Me"
      url = "/about-me"
      weight = 2

   [[menu.header]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1
